env:
  browser: true
  commonjs: true
  es6: true
extends: airbnb-base
globals:
  Atomics: readonly
  SharedArrayBuffer: readonly
parserOptions:
  ecmaVersion: 2018
rules:
  func-names:
    - error
    - never
  indent:
    - error
    - 4
  no-param-reassign:
    - error
    - ignorePropertyModificationsFor:
      - msg
  max-len:
    - error
    - 200

  global-require:
    - off
  vars-on-top:
    - off
  no-var:
    - off
  prefer-arrow-callback:
    - off
  prefer-destructuring:
    - off
  strict:
    - off
  dot-notation:
    - off
  eqeqeq:
    - off
  camelcase:
    - off
  no-bitwise:
    - off
  prefer-template:
    - off
